image:
  pullPolicy: IfNotPresent
  repository: ich777/debian-mirror
  tag: latest@sha256:f403f400567e6db13cad70f2927f8d1429bfc7462a6b54ad2785270f6de9b4a4
persistence:
  config:
    enabled: true
    mountPath: /debian-mirror/config
  data:
    enabled: true
    mountPath: /debian-mirror/data
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 980
        protocol: tcp
        targetPort: 980
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            APACHE2_PORT: "980"
            DATA_PERM: "770"
            FORCE_UPDATE: "false"
            UMASK: "0000"
